/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ParamProviderInterface extends ethers.utils.Interface {
  functions: {
    "REVISION()": FunctionFragment;
    "baseBorrowRate()": FunctionFragment;
    "excessSlope()": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "liquidationMargin()": FunctionFragment;
    "liquidationReward()": FunctionFragment;
    "maxLeverageFactor()": FunctionFragment;
    "maxLiquidationReward()": FunctionFragment;
    "maxPriceThreshold()": FunctionFragment;
    "maxRateMultiplier()": FunctionFragment;
    "minPositionDeposit()": FunctionFragment;
    "minWOWBalance(uint256)": FunctionFragment;
    "optimalSlope()": FunctionFragment;
    "optimalUtilization()": FunctionFragment;
    "overrideAddress(bytes32,address)": FunctionFragment;
    "overrideParam(bytes32,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "poolUtilizationAllowance()": FunctionFragment;
    "priceGuard()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reset(bytes32)": FunctionFragment;
    "swapRouter()": FunctionFragment;
    "traderProfitFee()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "treasureFactor()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "REVISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "baseBorrowRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excessSlope",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationMargin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxLeverageFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxLiquidationReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxRateMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minPositionDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minWOWBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "optimalSlope",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optimalUtilization",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "overrideAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "overrideParam",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolUtilizationAllowance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceGuard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "reset", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "traderProfitFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "treasureFactor",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "REVISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseBorrowRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excessSlope",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidationMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLeverageFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLiquidationReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRateMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minPositionDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minWOWBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optimalSlope",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optimalUtilization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "overrideAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "overrideParam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolUtilizationAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "priceGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "traderProfitFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasureFactor",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class ParamProvider extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ParamProviderInterface;

  functions: {
    REVISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    "REVISION()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    baseBorrowRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    "baseBorrowRate()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    excessSlope(overrides?: CallOverrides): Promise<[BigNumber]>;

    "excessSlope()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      owner: string,
      paramGovernance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initialize(address,address)"(
      owner: string,
      paramGovernance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    liquidationMargin(overrides?: CallOverrides): Promise<[BigNumber]>;

    "liquidationMargin()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    liquidationReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    "liquidationReward()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxLeverageFactor(overrides?: CallOverrides): Promise<[BigNumber]>;

    "maxLeverageFactor()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxLiquidationReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    "maxLiquidationReward()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxPriceThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    "maxPriceThreshold()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxRateMultiplier(overrides?: CallOverrides): Promise<[BigNumber]>;

    "maxRateMultiplier()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    minPositionDeposit(overrides?: CallOverrides): Promise<[BigNumber]>;

    "minPositionDeposit()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    minWOWBalance(
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "minWOWBalance(uint256)"(
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    optimalSlope(overrides?: CallOverrides): Promise<[BigNumber]>;

    "optimalSlope()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    optimalUtilization(overrides?: CallOverrides): Promise<[BigNumber]>;

    "optimalUtilization()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    overrideAddress(
      name: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "overrideAddress(bytes32,address)"(
      name: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    overrideParam(
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "overrideParam(bytes32,uint256)"(
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    poolUtilizationAllowance(overrides?: CallOverrides): Promise<[BigNumber]>;

    "poolUtilizationAllowance()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    priceGuard(overrides?: CallOverrides): Promise<[string]>;

    "priceGuard()"(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    reset(
      name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "reset(bytes32)"(
      name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<[string]>;

    "swapRouter()"(overrides?: CallOverrides): Promise<[string]>;

    traderProfitFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    "traderProfitFee()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    treasureFactor(overrides?: CallOverrides): Promise<[BigNumber]>;

    "treasureFactor()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  REVISION(overrides?: CallOverrides): Promise<BigNumber>;

  "REVISION()"(overrides?: CallOverrides): Promise<BigNumber>;

  baseBorrowRate(overrides?: CallOverrides): Promise<BigNumber>;

  "baseBorrowRate()"(overrides?: CallOverrides): Promise<BigNumber>;

  excessSlope(overrides?: CallOverrides): Promise<BigNumber>;

  "excessSlope()"(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    owner: string,
    paramGovernance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initialize(address,address)"(
    owner: string,
    paramGovernance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  liquidationMargin(overrides?: CallOverrides): Promise<BigNumber>;

  "liquidationMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

  liquidationReward(overrides?: CallOverrides): Promise<BigNumber>;

  "liquidationReward()"(overrides?: CallOverrides): Promise<BigNumber>;

  maxLeverageFactor(overrides?: CallOverrides): Promise<BigNumber>;

  "maxLeverageFactor()"(overrides?: CallOverrides): Promise<BigNumber>;

  maxLiquidationReward(overrides?: CallOverrides): Promise<BigNumber>;

  "maxLiquidationReward()"(overrides?: CallOverrides): Promise<BigNumber>;

  maxPriceThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  "maxPriceThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

  maxRateMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

  "maxRateMultiplier()"(overrides?: CallOverrides): Promise<BigNumber>;

  minPositionDeposit(overrides?: CallOverrides): Promise<BigNumber>;

  "minPositionDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

  minWOWBalance(
    leverageFactor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "minWOWBalance(uint256)"(
    leverageFactor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  optimalSlope(overrides?: CallOverrides): Promise<BigNumber>;

  "optimalSlope()"(overrides?: CallOverrides): Promise<BigNumber>;

  optimalUtilization(overrides?: CallOverrides): Promise<BigNumber>;

  "optimalUtilization()"(overrides?: CallOverrides): Promise<BigNumber>;

  overrideAddress(
    name: BytesLike,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "overrideAddress(bytes32,address)"(
    name: BytesLike,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  overrideParam(
    name: BytesLike,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "overrideParam(bytes32,uint256)"(
    name: BytesLike,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  poolUtilizationAllowance(overrides?: CallOverrides): Promise<BigNumber>;

  "poolUtilizationAllowance()"(overrides?: CallOverrides): Promise<BigNumber>;

  priceGuard(overrides?: CallOverrides): Promise<string>;

  "priceGuard()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "renounceOwnership()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  reset(
    name: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "reset(bytes32)"(
    name: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  "swapRouter()"(overrides?: CallOverrides): Promise<string>;

  traderProfitFee(overrides?: CallOverrides): Promise<BigNumber>;

  "traderProfitFee()"(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  treasureFactor(overrides?: CallOverrides): Promise<BigNumber>;

  "treasureFactor()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    REVISION(overrides?: CallOverrides): Promise<BigNumber>;

    "REVISION()"(overrides?: CallOverrides): Promise<BigNumber>;

    baseBorrowRate(overrides?: CallOverrides): Promise<BigNumber>;

    "baseBorrowRate()"(overrides?: CallOverrides): Promise<BigNumber>;

    excessSlope(overrides?: CallOverrides): Promise<BigNumber>;

    "excessSlope()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      owner: string,
      paramGovernance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address)"(
      owner: string,
      paramGovernance: string,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidationMargin(overrides?: CallOverrides): Promise<BigNumber>;

    "liquidationMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

    liquidationReward(overrides?: CallOverrides): Promise<BigNumber>;

    "liquidationReward()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxLeverageFactor(overrides?: CallOverrides): Promise<BigNumber>;

    "maxLeverageFactor()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxLiquidationReward(overrides?: CallOverrides): Promise<BigNumber>;

    "maxLiquidationReward()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxPriceThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    "maxPriceThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxRateMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    "maxRateMultiplier()"(overrides?: CallOverrides): Promise<BigNumber>;

    minPositionDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    "minPositionDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

    minWOWBalance(
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "minWOWBalance(uint256)"(
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    optimalSlope(overrides?: CallOverrides): Promise<BigNumber>;

    "optimalSlope()"(overrides?: CallOverrides): Promise<BigNumber>;

    optimalUtilization(overrides?: CallOverrides): Promise<BigNumber>;

    "optimalUtilization()"(overrides?: CallOverrides): Promise<BigNumber>;

    overrideAddress(
      name: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "overrideAddress(bytes32,address)"(
      name: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    overrideParam(
      name: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "overrideParam(bytes32,uint256)"(
      name: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    poolUtilizationAllowance(overrides?: CallOverrides): Promise<BigNumber>;

    "poolUtilizationAllowance()"(overrides?: CallOverrides): Promise<BigNumber>;

    priceGuard(overrides?: CallOverrides): Promise<string>;

    "priceGuard()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    reset(name: BytesLike, overrides?: CallOverrides): Promise<void>;

    "reset(bytes32)"(name: BytesLike, overrides?: CallOverrides): Promise<void>;

    swapRouter(overrides?: CallOverrides): Promise<string>;

    "swapRouter()"(overrides?: CallOverrides): Promise<string>;

    traderProfitFee(overrides?: CallOverrides): Promise<BigNumber>;

    "traderProfitFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    treasureFactor(overrides?: CallOverrides): Promise<BigNumber>;

    "treasureFactor()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    REVISION(overrides?: CallOverrides): Promise<BigNumber>;

    "REVISION()"(overrides?: CallOverrides): Promise<BigNumber>;

    baseBorrowRate(overrides?: CallOverrides): Promise<BigNumber>;

    "baseBorrowRate()"(overrides?: CallOverrides): Promise<BigNumber>;

    excessSlope(overrides?: CallOverrides): Promise<BigNumber>;

    "excessSlope()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      owner: string,
      paramGovernance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initialize(address,address)"(
      owner: string,
      paramGovernance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    liquidationMargin(overrides?: CallOverrides): Promise<BigNumber>;

    "liquidationMargin()"(overrides?: CallOverrides): Promise<BigNumber>;

    liquidationReward(overrides?: CallOverrides): Promise<BigNumber>;

    "liquidationReward()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxLeverageFactor(overrides?: CallOverrides): Promise<BigNumber>;

    "maxLeverageFactor()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxLiquidationReward(overrides?: CallOverrides): Promise<BigNumber>;

    "maxLiquidationReward()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxPriceThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    "maxPriceThreshold()"(overrides?: CallOverrides): Promise<BigNumber>;

    maxRateMultiplier(overrides?: CallOverrides): Promise<BigNumber>;

    "maxRateMultiplier()"(overrides?: CallOverrides): Promise<BigNumber>;

    minPositionDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    "minPositionDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

    minWOWBalance(
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "minWOWBalance(uint256)"(
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    optimalSlope(overrides?: CallOverrides): Promise<BigNumber>;

    "optimalSlope()"(overrides?: CallOverrides): Promise<BigNumber>;

    optimalUtilization(overrides?: CallOverrides): Promise<BigNumber>;

    "optimalUtilization()"(overrides?: CallOverrides): Promise<BigNumber>;

    overrideAddress(
      name: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "overrideAddress(bytes32,address)"(
      name: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    overrideParam(
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "overrideParam(bytes32,uint256)"(
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    poolUtilizationAllowance(overrides?: CallOverrides): Promise<BigNumber>;

    "poolUtilizationAllowance()"(overrides?: CallOverrides): Promise<BigNumber>;

    priceGuard(overrides?: CallOverrides): Promise<BigNumber>;

    "priceGuard()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    reset(
      name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "reset(bytes32)"(
      name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    "swapRouter()"(overrides?: CallOverrides): Promise<BigNumber>;

    traderProfitFee(overrides?: CallOverrides): Promise<BigNumber>;

    "traderProfitFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    treasureFactor(overrides?: CallOverrides): Promise<BigNumber>;

    "treasureFactor()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    REVISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "REVISION()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseBorrowRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baseBorrowRate()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    excessSlope(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "excessSlope()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      owner: string,
      paramGovernance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(address,address)"(
      owner: string,
      paramGovernance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    liquidationMargin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "liquidationMargin()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidationReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "liquidationReward()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxLeverageFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maxLeverageFactor()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxLiquidationReward(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxLiquidationReward()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxPriceThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maxPriceThreshold()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxRateMultiplier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "maxRateMultiplier()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minPositionDeposit(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "minPositionDeposit()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minWOWBalance(
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "minWOWBalance(uint256)"(
      leverageFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    optimalSlope(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "optimalSlope()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    optimalUtilization(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "optimalUtilization()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    overrideAddress(
      name: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "overrideAddress(bytes32,address)"(
      name: BytesLike,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    overrideParam(
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "overrideParam(bytes32,uint256)"(
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolUtilizationAllowance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "poolUtilizationAllowance()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceGuard(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "priceGuard()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    reset(
      name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "reset(bytes32)"(
      name: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "swapRouter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    traderProfitFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "traderProfitFee()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    treasureFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "treasureFactor()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
